export interface Theme {
  id: string;
  name: string;
  description: string;
  vars: Record<string, string>;
}

export const THEMES: Theme[] = [
  {
    id: 'controlroom',
    name: 'Control Room',
    description: 'Near-black base, restrained semantic palette. Current direction.',
    vars: {
      '--base': '#0E1114',
      '--panel': '#161A1E',
      '--border': '#262B31',
      '--text-primary': '#EDEFF1',
      '--text-muted': '#8A929C',
      '--text-dim': '#4A515A',
      '--green': '#33C481',
      '--amber-red': '#E5533D',
      '--amber': '#E8A33D',
      '--cyan': '#3FB6D6',
      '--violet': '#9A7FE0',
      '--neutral': '#4A515A',
      '--header-bg': '#161A1E',
      '--card-hover-border': '#3FB6D6',
      '--radius-card': '8px',
      '--radius-badge': '4px',
      '--font-display': "'JetBrains Mono', monospace",
      '--font-ui': "'Inter', sans-serif",
    },
  },
  {
    id: 'phosphor',
    name: 'Phosphor',
    description: 'Green-on-black terminal. Monochrome, CRT-era instrumentation.',
    vars: {
      '--base': '#020D05',
      '--panel': '#061009',
      '--border': '#0E2914',
      '--text-primary': '#A8F0B8',
      '--text-muted': '#4A8A5A',
      '--text-dim': '#1F4A28',
      '--green': '#39FF6A',
      '--amber-red': '#FF4D1C',
      '--amber': '#C8E820',
      '--cyan': '#39DFAA',
      '--violet': '#A87EFF',
      '--neutral': '#1F4A28',
      '--header-bg': '#040D06',
      '--card-hover-border': '#39FF6A',
      '--radius-card': '2px',
      '--radius-badge': '0px',
      '--font-display': "'JetBrains Mono', monospace",
      '--font-ui': "'JetBrains Mono', monospace",
    },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Engineering blueprint — deep navy base, white drafting lines.',
    vars: {
      '--base': '#06101E',
      '--panel': '#0B1929',
      '--border': '#1A3050',
      '--text-primary': '#D8E8F8',
      '--text-muted': '#6E90B0',
      '--text-dim': '#2E5070',
      '--green': '#4CDDAA',
      '--amber-red': '#FF5C3A',
      '--amber': '#FFBB33',
      '--cyan': '#5AC8FA',
      '--violet': '#B09AFF',
      '--neutral': '#2E5070',
      '--header-bg': '#080E1A',
      '--card-hover-border': '#5AC8FA',
      '--radius-card': '4px',
      '--radius-badge': '2px',
      '--font-display': "'JetBrains Mono', monospace",
      '--font-ui': "'Inter', sans-serif",
    },
  },
  {
    id: 'ember',
    name: 'Ember',
    description: 'Warm dark — charcoal base, amber-orange accents, ember glow.',
    vars: {
      '--base': '#110D0A',
      '--panel': '#1A1410',
      '--border': '#2E2318',
      '--text-primary': '#F5E6D0',
      '--text-muted': '#9A7E62',
      '--text-dim': '#4A3828',
      '--green': '#5EC46A',
      '--amber-red': '#FF5733',
      '--amber': '#FF9F1C',
      '--cyan': '#F4A261',
      '--violet': '#C77DFF',
      '--neutral': '#4A3828',
      '--header-bg': '#150F0B',
      '--card-hover-border': '#FF9F1C',
      '--radius-card': '8px',
      '--radius-badge': '4px',
      '--font-display': "'JetBrains Mono', monospace",
      '--font-ui': "'Inter', sans-serif",
    },
  },
  {
    id: 'clinical',
    name: 'Clinical',
    description: 'Light mode — medical device / lab instrument aesthetic.',
    vars: {
      '--base': '#F0F2F5',
      '--panel': '#FFFFFF',
      '--border': '#DDE1E7',
      '--text-primary': '#12171F',
      '--text-muted': '#5B6470',
      '--text-dim': '#9AA2AC',
      '--green': '#0F9B5A',
      '--amber-red': '#C93A20',
      '--amber': '#B87A00',
      '--cyan': '#0080A8',
      '--violet': '#6B50CC',
      '--neutral': '#9AA2AC',
      '--header-bg': '#FFFFFF',
      '--card-hover-border': '#0080A8',
      '--radius-card': '6px',
      '--radius-badge': '3px',
      '--font-display': "'JetBrains Mono', monospace",
      '--font-ui': "'Inter', sans-serif",
    },
  },
];

export function applyTheme(theme: Theme) {
  const root = document.documentElement;
  for (const [k, v] of Object.entries(theme.vars)) {
    root.style.setProperty(k, v);
  }
}
